project:
  type: website

website:
  title: "BlogCarbonleakage"
  navbar:
    left:
      - text: "Fugas de Carbon"
        file: about.qmd
  page-navigation: true

format:
  html:
    theme: flatly
    toc: true
    df-print: paged